# Generated by Django 4.2.10 on 2024-02-26 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField()),
                ('date', models.DateField()),
                ('justification', models.TextField()),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='professionals.professional')),
                ('suggestion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='suggestions.suggestion')),
            ],
        ),
    ]
