# Generated by Django 4.1 on 2024-02-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_professional_documents_professional_organizations'),
        ('suggestions', '0002_suggestion_document_suggestion_professional'),
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='voting',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='suggestions.suggestion'),
        ),
    ]
