# Generated by Django 4.1 on 2024-02-23 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_professionals'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='documents',
            field=models.ManyToManyField(related_name='professional_documents', to='documents.document'),
        ),
        migrations.AddField(
            model_name='professional',
            name='organizations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='professionals.organization'),
        ),
    ]
