# Generated by Django 4.2.10 on 2024-02-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='professionals',
            field=models.ManyToManyField(related_name='documents', to='professionals.professional'),
        ),
    ]
