# Generated by Django 4.1 on 2024-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='professionals',
            field=models.ManyToManyField(related_name='document_professionals', to='professionals.professional'),
        ),
    ]
