# Generated by Django 4.2.7 on 2024-02-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_professionals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
        migrations.AddField(
            model_name='document',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
