# Generated by Django 4.2.10 on 2024-03-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='professionals',
            field=models.ManyToManyField(related_name='documents', to='professionals.professional'),
        ),
    ]
