name: "游닀 Elaborar Documento"
description: "A침ade una tarea de elaboraci칩n de un Documento."
title: "[Documentation] "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        # **游닀 Elaborar Documento**
  - type: textarea
    id: document-description
    attributes:
      label: "Descripci칩n del Documento"
      description: "Proporciona un breve resumen del contenido del documento."
    validations:
      required: true
  - type: textarea
    id: document-context
    attributes:
      label: "Contexto Adicional"
      description: "A침ade cualquier otro contexto o informaci칩n adicional sobre el documento aqu칤."
    validations:
      required: false