name: "游눌 Prueba"
description: "Creaci칩n de pruebas para una Funcionalidad."
title: "[Test] "
labels: ["test"]
body:
  - type: markdown
    attributes:
      value: |
        # **游눌 Creaci칩n de Prueba**
  - type: textarea
    attributes:
      label: "쯈u칠 trabajos/pruebas se necesitan crear?"
      description: "Los trabajos o pruebas de CI que deben crearse."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Contexto Adicional"
      description: "A침ade cualquier otro contexto o informaci칩n adicional sobre el problema aqu칤."
    validations: 
      required: false
