# Generated by Django 4.2.10 on 2024-03-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_professionals'),
        ('professionals', '0002_delete_organization_professional_organizations'),
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='documents.document'),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='professionals.professional'),
        ),
    ]
