# Generated by Django 4.2.10 on 2024-03-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.AddField(
            model_name='professional',
            name='organizations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionals', to='organizations.organization'),
        ),
    ]
