# Generated by Django 4.2.10 on 2024-03-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_suggestion_document_suggestion_professional'),
        ('professionals', '0002_delete_organization_professional_organizations'),
        ('votings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='professionals.professional'),
        ),
        migrations.AddField(
            model_name='voting',
            name='suggestion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votings', to='suggestions.suggestion'),
        ),
    ]
