# Generated by Django 5.0.2 on 2024-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.CharField(max_length=255)),
                ('justification', models.TextField()),
                ('section', models.CharField(max_length=10)),
                ('page', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
